name: Linting

on: pull_request

jobs:
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/hydrogen"

            - run: npm ci

            - run: npm run lint:prettier:check
    pint:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: true
          matrix:
            php: [8.2]

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup PHP
            uses: shivammathur/setup-php@v2
            with:
              php-version: ${{ matrix.php }}
              extensions: json, dom, curl, libxml, mbstring
              coverage: none

          - name: Install Pint
            run: composer global require laravel/pint

          - name: Run Pint
            run: pint

          - name: Commit linted files
            uses: stefanzweifel/git-auto-commit-action@v5
    commitlint:
        name: Commitlint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/hydrogen"

            - run: npm ci

            - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

    secretlint:
        name: Secretlint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: "lts/hydrogen"

            - run: npm ci

            - run: npx secretlint --maskSecrets "**/*"
